Język [Python](https://pl.wikipedia.org/wiki/Python) jest uniwersalnym [językiem programowania wysokiego poziomu](https://pl.wikipedia.org/wiki/J%C4%99zyk_wysokiego_poziomu). Charakteryzuje się bardzo przejrzystą, klarowną i zwięzłą składnią. Język ten został stworzony w latach 90-tych XX wieku przez [Guido van Rossuma](https://gvanrossum.github.io//) z Holandii. Python umożliwia programowanie zarówno [imperatywne](https://pl.wikipedia.org/wiki/Programowanie_imperatywne) ([proceduralne](https://pl.wikipedia.org/wiki/J%C4%99zyk_proceduralny)), [obiektowe](https://pl.wikipedia.org/wiki/Programowanie_obiektowe) jak i [funkcyjne](https://pl.wikipedia.org/wiki/Programowanie_funkcyjne). Jest [językiem interpretowanym](https://pl.wikipedia.org/wiki/J%C4%99zyk_interpretowany) (w przeciewieństwie np. do języka C, który jest [językiem kompilowanym](https://pl.wikipedia.org/wiki/J%C4%99zyk_kompilowany)). Pliki zawierające kod języka Python są zapisywane na ogół z rozszerzeniem '.py', a w przypadku notatników pythonowych 'ipynb'. Do niedawna istniały dwie linie rozwojowe Pythona: 2 oraz 3. Aktualnie rozwijana jest wyłącznie wersja 3.

Pomocne strony:

* [Strona główna Pythona](https://www.python.org/)
* [The Python 3.8 Language Reference](https://docs.python.org/3.8/reference/index.html)
* [The Python tutorial](https://docs.python.org/3/tutorial/)
* [Inne tutoriale](https://www.google.com/search?client=firefox-b-d&q=python+tutorial)


## 1. Pakiety

[Standardowa biblioteka Pythona](https://docs.python.org/3/library/) zawiera zestaw funkcji podstawowych. Python został jednak wyposażony w możliwość rozszerzania jego funkcjonalności poprzez dodawanie bibliotek zewnętrznych w formie [pakietów](https://pypi.org/). Do wczytania konkretnego pakietu służy komenda `import`. W poniższym przykładzie wykorzystywany jest pakiet `sys`, który zawiera m.in. funkcję `version` zwracającą aktualnie używaną wersję interpretera. Dostęp do funkcji z pakietu wymaga poprzedzenia nazwy funkcji, nazwą pakietu, przy czym obie nazwy oddzielamy kropką. 

In [1]:
# sprawdzenie wersji interpretera
# wczytujemy pakiet sys
import sys 
# wywołujemy funkcję 'version' z pakietu 'sys', a jej wynik wyświetlamy
print(sys.version)

3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]


In [2]:
# pakiet 'math' zawiera przydatne funkcje matematyczne
import math
print(math.sin(math.pi*99),math.cos(math.pi/3))
print(math.pi)

-1.274499244004471e-14 0.5000000000000001
3.141592653589793


Każdy pakiet posiada swoją własną przestrzeń nazw. Oznacza to, że taka sama nazwa funkcji może występować w różnych pakietach. Dlatego właśnie nazwę funkcji poprzedza się nazwą pakietu. Nazwę pakietu wykorzystywanego w danej sesji można zmienić w następujący sposób:

In [3]:
import sys as gucio
print(gucio.version)
import math as m
print(m.sin(m.pi/3),m.cos(m.pi/3))

3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]
0.8660254037844386 0.5000000000000001


Możliwy jest także (choć należy go stosować ostrożnie) import funkcji z danego pakietu do głównej przestrzeni nazw - wówczas nie jest konieczne poprzedzanie nazwy funkcji prefiksem z nazwą pakietu:

In [4]:
from math import sin,cos,pi
print(sin(pi/4),cos(pi/4))

0.7071067811865476 0.7071067811865476


W powyższym przykładzie do głównej przestrzeni nazw importowane są trzy funkcje z pakietu `math`. Import wszystkich funkcji z danego pakietu uzyskamy w następujący sposób:

In [5]:
from math import *
print(sin(pi/333),cos(pi/3))

0.009434072225896754 0.5000000000000001


Funkcja `dir` wyświetla wszystkie funkcje z danego pakietu, zaś `help` pokazuje krótką pomoc dotyczącą danej funkcji:

In [6]:
import math
print(dir(math))
help(math.sin)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']
Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).



## 2. Zmienne i typy danych, podstawowe operatory

### 2.1 Nazwy, słowa kluczowe

Nazwy w Pythonie mogą zawierać następujące znaki: `a-z`, `A-Z`, `0-9` oraz niektóre znaki specjalne np. `_`. Nazwa zmiennej powinna rozpoczynać się małą literą, zaś nazwa klasy - wielką literą. 

Niektóre nazwy są zarezerwowane i nie powinny być używane jako nazwy zmiennych, zaliczamy do nich następujące ciągi znaków:

    and, as, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield
    


### 2.2 Przypisanie


Operatorem przypisania w Pythonie jest `=`. Ponieważ Python jest językiem z [dynamicznym typowaniem](https://pl.wikipedia.org/wiki/Typowanie_dynamiczne), nie ma konieczności deklarowania typu zmiennej (pierwsze przypisanie jest jednocześnie deklaracją zmiennej). Funkcja `print` wyświetla w konsoli wyliczoną wartość swoich argumentów, zaś`type` zwraca typ zmiennej.


In [7]:
# przypisanie zmiennej
x = 1
print(x, type(x))
type(x)

1 <class 'int'>


int

Kolejne przypisanie wartości tej samej zmiennej, zmienia jej wartość

In [8]:
x = 2.0
x
type(x)

float

### 2.3 Podstawowe typy danych numerycznych

Podstawowymi typami danych numerycznych są typy: całkowity, zmiennoprzecinkowy, logiczny, zespolony. Typ danych jest określany automatycznie na podstawie formy wyrażenia znajdującego się po prawej stronie znaku przypisania  `=`.

In [9]:
# typ całkowity (integer)
x = 1
type(x)

int

In [10]:
# typ zmiennoprzecinkowy (float)
x = 1.0
type(x)

float

In [11]:
# typ logiczny (boolean)
b1 = True
b2 = False

type(b1)


bool

In [12]:
# typ zespolony (complex) uwaga: `j` oznacza jednostkę urojoną
x = 1.0 - 1.0j
print(x, x.real, x.imag)
type(x)

(1-1j) 1.0 -1.0


complex

In [13]:
x = 1.0
# sprawdzenie czy zmienna x jest tyu float, int
print(type(x) is int)
print(type(x) is float)
print(isinstance(x, float))
type(x) is float

False
True
True


True

### 2.4 Operatory arytmetyczne i porównania

Operatory arytmetyczne są oznaczane typowo, podobnie jak w innych językach programowania:

`+`, `-`, `*`, `/`, `//` (część całkowita/cecha/podłoga z dzielenia), `**` (potęga)


In [14]:
1 + 2, 1 - 2, 1 * 2, 1 / 2, 1 // 2

(3, -1, 2, 0.5, 0)

In [15]:
1.0 + 2.0, 1.0 - 2.0, 1.0 * 2.0, 1.0 / 2.0, 1.0 // 2.0

(3.0, -1.0, 2.0, 0.5, 0.0)

Operatory logiczne to `and`, `not`, `or`. 

In [16]:
True and False

False

In [17]:
not False

True

In [18]:
True or False

True

Operatory porównania to `>`, `<`, `>=` (większe-równe), `<=` (mniejsze-równe), `==` równość, `is` tożsamość.

In [19]:
2 > 1, 2 < 1

(True, False)

In [20]:
2 > 2, 2 < 2

(False, False)

In [21]:
# równość (co do wartości)
[1,2] == [1,2]

True

In [22]:
# czy obiekty są tożsame ?
l1 = l2 = [1,2]

l1 is l2


True

Operator `==` porównuje wartości dwóch obiektów, jeśli są równe, zwraca wartość `True`. Operator `is` sprawdza, czy nazwy po obu stronach odnoszą się do tego samego obiektu (ten sam obiekt może nosić różne nazwy). Poniższy przykład ilustruje różnicę między `==` oraz `is`

In [23]:
z1 = [1,2]
z2 = [1,2] 
z3 = z2
# obie listy mają takie same wartości
print(z1 == z2)
# ale to są różne listy 
print(z1 is z2)
# natomiast te dwie zmmienne to tak naprawdę ta sama lista
print(z2 is z3)

True
False
True


### 2.5 Typy złożone: ciągi znaków, listy, słowniki

Typem danych przeznaczony do przechowywania tekstów są ciągi (łańcuchy) znaków (`string`)

In [24]:
s = "Dzień Dobry"
type(s)

str

In [25]:
# długość łańcucha znaków
print("Łańcuch <<", s, ">> ma długość", len(s), "znaków.")

Łańcuch << Dzień Dobry >> ma długość 11 znaków.


In [26]:
# podmiana fragmentu łańcucha znaków
s2 = s.replace("Dobry", "tygodnia")
print(s2)

Dzień tygodnia


Do pojedyńczego znaku w ciągu odwołujemy się poprzez `[]` (indeksowanie startuje od `0` tak jak np. w języku C; ale już nie tak jak w Matlab-ie !):

In [27]:
s[0]

'D'

Ujemna wartość indeksu oznacza numer elementu liczony *od tyłu*.

In [28]:
s[-2]

'r'

Używając składni `[start:stop]`, uzyskuje się fragment ciągu składający się ze znaków od indeksu`start` do indeksu `stop-1` (znak o indeksie `stop` nie jest tam zawarty):

In [29]:
s[0:5]

'Dzień'

In [30]:
s[4:5]

'ń'

Pominięcie `start` i/lub `stop` z `[start:stop]` daje w efekcie przyjęcie skrajnych indeksów: `[:stop]` - od pierwszego znaku do znaku o indeksie `stop-1`; `[start:]` - od znaku o indeksie `start` do ostatniego znaku.

In [31]:
s[:5]

'Dzień'

In [32]:
s[6:]

'Dobry'

In [33]:
s[:]

'Dzień Dobry'

Łańcuchy znaków można łączyć dodając je do siebie.

In [34]:
s3 = "Dzień" + " " + "Dobry"
s3

'Dzień Dobry'

In [35]:
s4 = s3[:3] + s3[4:7] + "y" + s3[8:]
s4

'Dziń Dybry'

Można także indeksować w sposób następujący: `[start:stop:krok]` (standardowo `krok` jest równy 1, wtedy można go pominąć):

In [36]:
s[::2]

'DińDby'

In [37]:
s[::1]

'Dzień Dobry'

Łańcuchy znaków mogą stanowić jeden z argumentów funkcji `print`.

In [38]:
print("str1", "str2", "str3")  # komenda print drukuje teksty będące jej argumentami, oddzielonymi przecinkami

str1 str2 str3


In [39]:
print("str1", 1.0, False, -1j)  # każdy inny typ danych jest przekształcany na łańcuch znaków

str1 1.0 False (-0-1j)


In [40]:
print("str1" + "str2" + "str3") # trzy łańcuchy połączone w jeden, który jest tu jedynym argumentem 

str1str2str3


In [41]:
print("wartosc = %f" % 1.0)       # formatowanie w stylu języka C

wartosc = 1.000000


In [42]:
# tworzenie łańcuch znaków, a dopiero potem drukowanie
s2 = "wartosc1 = %.2f. wartosc2 = %d" % (3.1415, 1.5)

print(s2)

wartosc1 = 3.14. wartosc2 = 1


In [43]:
# to samo uzyskane w inny sposób
s3 = 'wartosc1 = {0}, wartosc2 = {1}'.format(3.1415, 1.5)

print(s3)

wartosc1 = 3.1415, wartosc2 = 1.5


### 2.6 Listy

Listy służą do przechowywania większej liczby danych - w ich skład mogą wchodzić elementy dowolnych typów.

In [44]:
l = [1,2,3,4]

print(type(l))
print(l)

<class 'list'>
[1, 2, 3, 4]


Indeksowanie list następuje w identyczny sposób do indeksowania ciągów znaków:

In [45]:
print(l)

print(l[1:3])

print(l[::2])

[1, 2, 3, 4]
[2, 3]
[1, 3]


Lista o elementach niejednorodnych (różne typy danych):

In [46]:
l = [1, 'a', 1.0, 1-1j]

print(l)

[1, 'a', 1.0, (1-1j)]


Listy mogą być zagnieżdżone:

In [47]:
lista_zag = [1, [2, [3, [4, [5]]]]]

lista_zag

[1, [2, [3, [4, [5]]]]]

Operator `in` służy do testowania czy element znajduje się na liście.

In [48]:
miasta = ['Warszawa', 'Kraków', 'Toruń']
print('Toruń' in miasta)
print('Poznań' in miasta)

True
False


Funkcja `list` zwraca listę na którą przekształcany jest obiekt będący jej argumentem. Przykładowo, możemy w ten sposób przeksztacić w listę ciąg znaków:

In [49]:
# konwersja typu
s2 = list(s)

s2

['D', 'z', 'i', 'e', 'ń', ' ', 'D', 'o', 'b', 'r', 'y']

Element można dodać do listy metodą `append`

In [50]:
# tworzenie listy pustej
l = []

# dodawanie elementów do listy
l.append("A")
l.append("dwa")
l.append(3)
l.append([4.0])

print(l)

['A', 'dwa', 3, [4.0]]


In [51]:
tablica1 = [1,2,3,4]
tablica2 = []
tablica2.append(5)
tablica2.append(6)
print(tablica1, tablica2)
print(tablica1[3],tablica2[1])

[1, 2, 3, 4] [5, 6]
4 6


Elementy listy mogą być modyfikowane.

In [52]:
l[1] = 2
l[3] = "cztery"

print(l)

['A', 2, 3, 'cztery']


In [53]:
l[0:4] = ["l", "i", "s", "t"]
l.append("a")
print(l)

['l', 'i', 's', 't', 'a']


Metoda `insert` służy do wstawiania nowego elementu we wskazanym miejscu listy, z przesunięciem pozostałych elementów.

In [54]:
l.insert(0, "w")
l.insert(1, "s")
l.insert(2, "t")
l.insert(3, "a")
l.insert(4, "w")
l.insert(5, " ")

print(l)

['w', 's', 't', 'a', 'w', ' ', 'l', 'i', 's', 't', 'a']


Metoda `remove` usuwa element listy o najniższym indeksie będący jej argumentem.   

In [55]:
l.remove("w")
print(l)
l.remove("w")
print(l)

['s', 't', 'a', 'w', ' ', 'l', 'i', 's', 't', 'a']
['s', 't', 'a', ' ', 'l', 'i', 's', 't', 'a']


Instrukcja `del` usuwa element listy o konkretnym indeksie lub zakresie indeksów:

In [56]:
del l[:4]

print(l)

['l', 'i', 's', 't', 'a']


Listę można także odwrócić lub posortować. 

* Uwaga 1: poniższy sposób wykonywania operacji polega na wywołaniu metody konkretnego obiektu listy, stąd wynik jest zapisany jako ta sama lista. 
* Uwaga 2: sortowanie listy jest możliwe jedynie jeśli lista zawiera elementy tego samego typu, dla którego możliwe jest jednoznaczne porównanie dwóch obiektów. W przeciwnym razie próba sortowania zakończy się komunikatem błedu.

In [57]:
# odwracanie listy
l.reverse()
print(l)
l.reverse()
print(l)
# sortowanie listy
l.sort()
print(l)

['a', 't', 's', 'i', 'l']
['l', 'i', 's', 't', 'a']
['a', 'i', 'l', 's', 't']


### 2.7 Krotki

*Krotki* są koncpecyjnie podobne do list, z tą różnicą, że są *niemodyfikowalne*. Krotki są tworzone z wykorzystaniem składni
 `(..., ..., ...)` lub `..., ...`.

In [58]:
punkt = (15, 20)

print(punkt, type(punkt))

(15, 20) <class 'tuple'>


In [59]:
punkt = 15, 20

print(punkt, type(punkt))

(15, 20) <class 'tuple'>


Stosując poniższa składnię, wartości kolejnych elementów krotki są przypisywane kolejnym zmiennym. Jednocześnie próba przypisania wartości do elementu krotki kończy się błędem. 

In [60]:
x, y = punkt

print("x =", x)
print("y =", y)

punkt = (1, 5);

x = 15
y = 20


### 2.8 Słowniki

Słowniki są także podobne do list, z tą tym razem różnicą, że ich elementami są pary klucz-wartość. Definiując słownik stosuje się następującą składnię: `{klucz1 : wartosc1, ...}`:

In [61]:
par = {"parametr1" : 1.0,
       "parametr2" : 2.0,
       "parametr3" : 3.0,}

print(type(par))
print(par)

<class 'dict'>
{'parametr1': 1.0, 'parametr2': 2.0, 'parametr3': 3.0}


In [62]:
print("parametr1 = " + str(par["parametr1"]))
print("parametr2 = " + str(par["parametr2"]))
print("parametr3 = " + str(par["parametr3"]))

parametr1 = 1.0
parametr2 = 2.0
parametr3 = 3.0


In [63]:
par["parametr1"] = "A"
par["parametr2"] = "B"

# nowy element
par["parametr4"] = "D"

print("parametr1 = " + str(par["parametr1"]))
print("parametr2 = " + str(par["parametr2"]))
print("parametr3 = " + str(par["parametr3"]))
print("parametr4 = " + str(par["parametr4"]))

parametr1 = A
parametr2 = B
parametr3 = 3.0
parametr4 = D


## 3. Instrukcje sterujące, funkcje, wyjątki

### 3.1 Instrukcje warunkowe: if, elif, else

Instrukcje warunkowe w Pythonie tworzymy korzystając z tradycyjnych wyrażeń `if`, `elif` (else if), `else`:

In [64]:
2 >= 2, 2 <= 2

(True, True)

In [65]:
wyrazenie1 = False
wyrazenie2 = True

if wyrazenie1:
    print("wyrazenie1 jest prawdziwe")
elif wyrazenie2:
    print("wyrazenie2 jest prawdziwe")
    
else:
    print("oba wyrazenia są fałszywe")
    print("ala ma kota")

wyrazenie2 jest prawdziwe


Bloki komend w Pythonie są wyróżniane poprzez wcięcie, składające się najczęściej z czterech znaków spacji. W przeciwieństwie do innych języków programowania nie są stosowane żadne ograniczniki, takiej jak np. w języku C znaki `{` i `}`. Dzięki obowiązkowym wcięciom kod Python'a jest zawsze przejrzysty i wygodny do analizy. Poniższe przykłady pokazują różne kombinacje wcięć, definiujących na różne sposoby bloki komend.

In [66]:
wyrazenie1 = wyrazenie2 = True

if wyrazenie1:
    if wyrazenie2:
        print("oba wyrazenia: wyrazenie1 and wyrazenie2 są prawdziwe")

oba wyrazenia: wyrazenie1 and wyrazenie2 są prawdziwe


Inny przykład

In [67]:
x = 11
if x%2 != 1:
    prefiks = ""
else:
    prefiks = "nie"
print(str(x) + " to liczba " + prefiks + "parzysta")

11 to liczba nieparzysta


Brak wcięcia w miejscu, gdzie powinno się ono znaleźć skutkuje komunikatem błędu.

In [68]:
if wyrazenie1:
    if wyrazenie2:
        print("oba wyrazenia: wyrazenie1 and wyrazenie2 są prawdziwe")  # BŁĄD !

oba wyrazenia: wyrazenie1 and wyrazenie2 są prawdziwe


Z drugiej strony, nieuważne wstawienie lub usunięcie wcięcia zmienia sens danego fragmentu kodu.

In [69]:
wyrazenie1 = True 

if wyrazenie1:
    print("wyrazenie1 jest prawdziwe")
    
    print("cały czas wewnątrz bloku")

wyrazenie1 jest prawdziwe
cały czas wewnątrz bloku


In [70]:
if wyrazenie1:
    print("wyrazenie1 jest prawdziwe")
    
print("na zewnątrz bloku")

wyrazenie1 jest prawdziwe
na zewnątrz bloku


Instrukcja `elif` to warunek alternatywny, testowany jeśli główny warunek instrukcji `if` nie jest spełniony. 


In [71]:
miasta = ['Warszawa','Krakow','Poznan']
panstwa = ['Polska','Norwegia','Holandia']
slowo = 'Polska'
if slowo in miasta:
    print('miasto')
elif slowo in panstwa:
    print('panstwo')
else:
    print('ani miasto ani panstwo')

panstwo


Warunek logiczny może być warunkiem składającym się w wielu pojedynczych połączonych spójnikami logicznymi `and`, `or` i `not`. 

In [72]:
imie = 'Jan'
wiek = 20
if imie == "Jan" and wiek < 18:
    print('Młody Jan')
if imie != "Jan" or not(wiek >= 18):
    print('Młody albo nie-Jan')
else:
    print('Stary Jan')

Stary Jan


### 3.2 Pętle

Dwie podstawowe pętle w języku Python to pętle `for` oraz `while`. Pętle moga być definiowane na różne sposoby.

#### **Pętla `for`**:

Pętla `for` jest podstawowym narzędziem służącym do realizacji powtarzalnych sekwencji czynności. Pętla `for` iteruje po elementach listy znajdującej się po słowie kluczowym `in` i wykonuje wcięty blok znajdujący się poniżej dla każdego elementu listy. W instrukcji `for` można użyć dowolnej listy 

In [73]:
for x in [1,2,3]:
    print(x)

1
2
3


In [74]:
for word in ["wprowadzenie", "do", "języka", "Python"]:
    print(word)

wprowadzenie
do
języka
Python


In [75]:
for x in [1,'znaki',['lis','ta']]:
    print(x)

1
znaki
['lis', 'ta']


Aby uzyskać typowe w innych językach programowania iterowanie poprzez krokową modyfikację wartości zmiennej iterowanej wykorzystuje się tzw. iteratory czyli obiekty pozwalające na uzyskiwanie kolejnych wartości zmiennej sterującej. Iterator generujący kolejne liczby jest uruchamiany poprzez funkcję `range`.  

In [76]:
start = 2
stop = 32
krok = 2
range(start, stop, krok)

range(2, 32, 2)

Aby zobaczyć kolejne wartości generowane przez iterator, należy wygenerować stosowaną listę. Funkcja `list` służy, w poniższym przykładzie, do konwersji iteratora na listę.

In [77]:
print(list(range(-20,3)))

[-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2]


Pojedynczy argument iteratora oznacza, że domyślnie jako wartość początkowa przyjmowane jest 0, zaś krok wynosi 1.

In [78]:
for x in range(4): # startujemy od 0
    print(x)

0
1
2
3


Uwaga: `range(4)` nie zawiera 4 !

W przypadku dwuargumentowego iteratora, domyślnie przyjmuje się wartość kroku równą 1. 

In [79]:
for x in range(-3,3):
    print(x)

-3
-2
-1
0
1
2


In [80]:
wartosci = [1,2,4,5,7,8]
print("pierwsza pętla")
for x in wartosci:
    print(x)
wynik = 0;
print("druga pętla")
for y in range(5):
    wynik = wynik + y
print(wynik)

pierwsza pętla
1
2
4
5
7
8
druga pętla
10


>**Zadanie** Napisz pętlę w której obliczany jest ciąg Fibonacciego (pierwszy wyraz to 0, drugi 1, a każdy kolejny jest sumą dwóch poprzednich) o zadanej długości n.


In [81]:
n = 20 # długość ciągu
# miejsce na rozwiązanie zadania



Niekiedy możliwe jest wprowadzenie dwóch zmiennych zmieniających swoje wartości w trakcie iteracji (zmiennych sterujących pętli). Jest tak np. w przypadku iterowania po elementach słownika:

In [82]:
par = {"parametr1" : 1.0,
          "parametr2" : 2.0,
          "parametr3" : 3.0,}
for klucz, wartosc in par.items():
    print(klucz + " = " + str(wartosc))

parametr1 = 1.0
parametr2 = 2.0
parametr3 = 3.0


Jednoczesny dostęp do elementu listy oraz jego indeksu daje funkcja `enumerate`, której argumentem jest iterator `range`.

In [83]:
for idx, x in enumerate(range(-3,3)):
    print(idx, x)

0 -3
1 -2
2 -1
3 0
4 1
5 2


Argumentem `enumerate` może być także lista.

In [84]:
for idx, x in enumerate([1,'dwa','3']):
    print(idx, x)

0 1
1 dwa
2 3


Pętla `for` może być wykorzystana do inicjalizacji listy.

In [85]:
l1 = [x**2 for x in range(0,5)]

print(l1)

[0, 1, 4, 9, 16]


#### **Pętla `while`**:

Pętlę `while` stosujemy najczęściej, gdy liczba iteracji nie jest zadana z góry (znana przed uruchomienim pętli), lecz wynika z pewnych warunków, które zachodzą w trakcie iterowania. W jej przypadku wykonywanie kolejnych iteracji jest realizowane jeśli spełniony jest określony warunek.

In [86]:
i = 0

while i < 5:
    print(i)   
    i = i + 1  
print("gotowe")

0
1
2
3
4
gotowe


Komenda `print("gotowe")` znajduje się poza pętlą `while` na co wskazuje brak stosownego wcięcia.

W obu rodzajach pętlu, do zakończenia procesu iterowania (niezależnie od warunku logicznego) pętli służy instrukcja `break`. Instrukcja `continue` umożliwia opuszczenie bloku komend znajdujących się poniżej tej instrukcji i przejście do kolejnej iteracji pętli.

In [87]:
licznik = 0
while True:
    print(licznik),
    licznik += 2
    if licznik >= 10:
        break

print("\n")

for x in range(10):
    if x % 2 == 0:
        continue
    print(x)


0
2
4
6
8


1
3
5
7
9


### 3.3 Funkcje

Funkcje w Pythonie są definiowane z wykorzystaniem słowa kluczowego `def`, po którym następuje nazwa funkcji oraz lista arumentów w nawiasach okrągłych i znak dwukropka `:`. Ciało funkcji to blok komend znajdujący poniżej (podobnie jak w przypadku instrukcji warunkowych i pętli wymagane jest wcięcie !).

In [88]:
def func0():   
    print("test")

In [89]:
func0()

test


Na początku ciała funkcji, przed innymi instrukcjami, można umieścić tekst wyświetlany jako pomoc danej funkcji. 

In [90]:
def func1(s):
    """
    Drukuje ciąg znaków s oraz jego długość 
    """
    
    print(s + " składa się z " + str(len(s)) + " znaków")

In [91]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Drukuje ciąg znaków s oraz jego długość



In [92]:
func1("test")

test składa się z 4 znaków


Wartość zwracana przez funkcję powinna być umieszczona po słowie kluczowym `return`:

In [93]:
def kwadrat(x):
    """
    Zwraca kwadrat x.
    """
    return x ** 2

In [94]:
kwadrat(4)

16

Funkcja może zwracać większą liczbę wartości.

In [95]:
def potegi(x):
    """
    Funkcja zwraca kilka potęg x.
    """
    return x ** 2, x ** 3, x ** 4

In [96]:
potegi(3)

(9, 27, 81)

In [97]:
x2, x3, x4 = potegi(3)

print(x3)

27


W definicji funkcji można podawać domyślne wartości argumentów.

In [98]:
def myfunc(x, p=2, debug=False):
    if debug:
        print("wyznaczanie wartości x = " + str(x) + " podniesionej do potęgi p = " + str(p))
    return x**p

In [99]:
myfunc(5)

25

In [100]:
myfunc(5, debug=True)

wyznaczanie wartości x = 5 podniesionej do potęgi p = 2


25

Wywołując funkcję, jej argumenty można podać wraz z nazwami zmiennych, którym są przypisywane. W takiej sytuacji kolejność argumentów może być dowolna.

In [101]:
myfunc(p=3, debug=True, x=7)

wyznaczanie wartości x = 7 podniesionej do potęgi p = 3


343

### 3.4 Funkcje lambda

W Pythonie możemy tworzyć funkcje nienazwane korzystając z komendy `lambda`:

In [102]:
f1 = lambda x: x**2
    
# co jest równoważne 

def f2(x):
    return x**2

In [103]:
f1(2), f2(2)

(4, 4)

Może to być wykorzystane w sytuacji gdy funkcja stanowi argument innej funkcji i nie jest wykorzystywana w żaden inny sposób:

In [104]:
# map jest wbudowaną funcją Pythona
list(map(lambda x: x**2, range(-3,4)))

[9, 4, 1, 0, 1, 4, 9]

W powyższym przykładzie wykorzystywana jest funkcja `map`, której działanie polega na wywołaniu innej funkcji, która jest jej pierwszym argumentem (funkcja `lambda`), kolejno dla wszystkich elementów iteratora `range` będącej jej drugim argumentem. Wynik działania funkcji `map` jest następnie argumentem funkcji list, która umożliwia zapisanie wyniku w formie listy. 

### 3.5 Wyjątki

Do obsługi wyjątków w Pythonie wykorzystuje się komendy `try:`, rozpoczynającą blok w którym błąd może wystapić, oraz `except:` po której następuje blok osługi błędu.

In [105]:
try:
    print("test")
except:
    print("Wyjątek złapany !")

test


In [106]:

    print(test)


NameError: name 'test' is not defined

In [103]:
try:
    ptint("test")
except:
    print("Wyjątek złapany !")

Wyjątek złapany !


Obsługę błędu można uruchomić korzystając z komendy `raise`. W ten sposób może zostać zgłoszony wyjątek pomimo braku faktycznego błędu w programie.

In [109]:
raise Exception("opis błędu")

Exception: opis błędu

In [110]:
try:
    raise Exception("opis błędu")
    print("test")
except:
    print("Wyjątek złapany !")

Wyjątek złapany !


## 4. Pakiet Numpy

Podstawowy zasób struktur danych języka Python nie zawiera struktur kluczowych dla wszelkiego rodzaju obliczeń numerycznych - wektorów i tablic (macierzy). Przyczyną takiego stanu rzeczy jest fakt, iż język Python w swojej pierwotnej wersji nie był przeznaczony do tego rodzaju obliczeń. Braki w zakresie odpowiednich struktur danych oraz istotnych procedur obliczeń numerycznych zostały uzupełnione wraz z pojawieniem się pakietu `Numpy` (https://numpy.org/). Jak każdy pakiet języka Python, także i `numpy` wymaga wcześniejszego zaimportowania.

In [104]:
import numpy as np

Macierze w pakiecie `numpy` moga być incjowane na kilka sposobów:

* na podstawie listy lub krotki wartości
* użwając funkcji przeznaczonych do tworzenia macierzy (np. `arange`, `linspace`)
* wczytując jej elementy z dysku

### 4.1 Tworzenie macierzy na podstawie list

Do utworzenia nowej macierzy można wykorzystać funkcję `numpy.array` (lub`np.array` stosując zwyczajowy prefiks pakietu), której argumentem jest lista.

In [105]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [106]:
# argumentem w tym przypadku jest lista list - w efekcie powstaje macierz dwuwymiarowa
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

Argumentem `numpy.array` może być także lista krotek.

In [124]:
M2 = np.array([(1., 2.0), (3.0, 4.0)])

M2

array([[1., 2.],
       [3., 4.]])

Obie macierze `v` i `M` są typu `ndarray`, zaimplementowanego w pakiecie `numpy`.

In [125]:
type(v), type(M), type(M2)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

Macierz jest obiektem. Informację o rozmiarze macierzy uzyskujemy stosując metodę `.shape`.

In [126]:
print(v.shape)
print(M.shape)
print(M2.shape)

(4,)
(2, 2)
(2, 2)


Informację o liczbie elementów macierzy zwraca metoda `ndarray.size`, zaś o liczbie wymiarów: `ndarray.ndim`:

In [127]:
print(v.ndim,v.size)
print(M.ndim,M.size)

1 4
2 4


Identyczne efekty można uzyskać stosując funkcje `numpy.shape`, `numpy.size`, `numpy.ndim`, których argumentem jest macierz. 

In [128]:
print(np.shape(M),",",np.ndim(M),",",np.size(M))

(2, 2) , 2 , 4


In [129]:
np.size(M)

4

Macierz jest homogeniczna pod względem wartości elementów (inaczej niż lista czy krotka), czyli wszystkie jej elementy są, z definicji, tego samego typu. Typ danych elementów macierzy zależy od formatu liczb użytych w procesie inicjacji macierzy. Typ danych zwraca metoda `numpy.dtype`.

In [130]:
M.dtype

dtype('int64')

In [131]:
M2.dtype

dtype('float64')

Typ danych można także narzucić podczas tworzenia macierzy, korzystając z argumentu `dtype`: 

In [132]:
M1 = np.array([[1, 2], [3, 4]], dtype=complex)

M1

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

np.logspaceZ komendą `dtype` mogą być używane wszystkie typy danych: `int`, `float`, `complex`, `bool`, `object`, itd.

Dodatkowo można określić rozmiar danych (w bitach): `int64`, `int16`, `float128`, `complex128`.

Poniższe metody służą do pobierania parametrów macierzy: liczby bajtów na element, liczbę bajtów zajmowanych przez całą macierz oraz liczbę jej wymiarów.

In [160]:
print(M.itemsize, M.nbytes, M.ndim)

8 72 2


### 4.2 Tworzenie macierzy przy pomocy funkcji

Macierze mogą być także tworzone z wykorzystaniem funkcji, które wypełniają macierz wartościami, zgodnie z ustaloną zasadą. 

Funkcja `arange` zwraca ciąg wartości o zadanej wartości początkowej, górnym ograniczeniu oraz kroku.

In [133]:
x = np.arange(0, 10, 1) # argumenty: start, stop, krok

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

Funkcje `linspace` and `logspace` generują strukturę dwuwymiarową o próbkowaniu liniowym lub logarytmicznym.

In [135]:
# w przypadku linspace, wyjściowa macierz zawiera oba ograniczenia - dolne i górne
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [138]:
np.logspace(0, 10, 10, base=2)

array([1.00000000e+00, 2.16011948e+00, 4.66611616e+00, 1.00793684e+01,
       2.17726400e+01, 4.70315038e+01, 1.01593667e+02, 2.19454460e+02,
       4.74047853e+02, 1.02400000e+03])

Funkcja `mgrid` zwraca dwie macierze zawierające współrzędne x oraz y siatki próbkowania.

In [139]:
x, y = np.mgrid[0:5, 0:5] 

In [140]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [141]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Funkcje `rand` oraz `randn` zwracają macierze wartości losowych z zakresu 0...1, przy czym efektem tej pierwszej jest dystrybcja zgodna z rozkładem jednostajnym, zaś drugiej - dystrybucja zgodna z rozkładem normalnym.

In [142]:
# liczby losowe z zakresu [0,1] - rozkład jednostajny
np.random.rand(5,5)

array([[0.72145397, 0.76593952, 0.35466721, 0.84639162, 0.04481962],
       [0.51631334, 0.75143676, 0.91010125, 0.72968557, 0.30686834],
       [0.65663456, 0.98451028, 0.6430116 , 0.811326  , 0.94040083],
       [0.11362194, 0.61332157, 0.25130623, 0.90298951, 0.03489146],
       [0.50829156, 0.98655609, 0.44641751, 0.04644817, 0.64541383]])

In [143]:
# liczby losowe z zakresu [0,1] - rozkład normalny: średnia = 0, odchylenie standardowe = 1
np.random.randn(5,5)

array([[-0.33477774,  0.10094758, -0.22958812, -0.88644384,  1.79799203],
       [-1.15560685, -0.57375426, -1.34647222,  0.88569931,  0.41357664],
       [ 0.62508264,  0.40064152,  1.23522494,  1.01822123, -1.3351352 ],
       [ 0.35744241, -1.01993509,  1.18745452,  1.1853782 ,  0.05413948],
       [-0.00253716,  0.08679502, -2.0729299 , -0.30498994,  0.90252228]])

Funkcja `diag` służy do tworzenia macierzy diagonalnej.

In [144]:
# macierz diagonalna
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [145]:
# macierz diagonalna z przesunięciem diagonali
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

Funkcje `zeros` oraz `ones` zwracają macierze składające się z samych zer i jedynek.

In [146]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [147]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 4.3 Zapis i odczyt macierzy z dysku

Komenda `numpy.savetxt` służy do zapisu macierzy w formacie `.csv`.:

In [148]:
import numpy as np
M = np.random.rand(3,3)
np.savetxt("macierz.csv", M)
M

array([[0.87590557, 0.95846158, 0.72842298],
       [0.4142462 , 0.0427534 , 0.80001726],
       [0.99148644, 0.31718671, 0.44461764]])

Tak zapisane dane można wczytać przy pomocy komendy `numpy.loadtxt`

In [149]:
M1 = np.loadtxt("macierz.csv")
M1

array([[0.87590557, 0.95846158, 0.72842298],
       [0.4142462 , 0.0427534 , 0.80001726],
       [0.99148644, 0.31718671, 0.44461764]])

Pakiet `numpy` umożliwia także zapis macierzy w swoim własnym formacie przy użyciu komend `numpy.save` and `numpy.load`:

In [150]:
np.save("macierz.npy", M)

In [151]:
np.load ("macierz.npy")


array([[0.87590557, 0.95846158, 0.72842298],
       [0.4142462 , 0.0427534 , 0.80001726],
       [0.99148644, 0.31718671, 0.44461764]])

### 4.4 Indeksowanie macierzy

Indeksowanie macierzy następuje przez podanie współrzędnych elementu/ów w nawiasach kwadratowych:

In [152]:
print(M)
# element o wsp. 1,2 (indeksowanie zaczynamy od 0,0)
M[1,2]

[[0.87590557 0.95846158 0.72842298]
 [0.4142462  0.0427534  0.80001726]
 [0.99148644 0.31718671 0.44461764]]


0.8000172648761714

Pominięcie drugiego indeksu daje w efekcie wiersz o numerze równym podanemu, pojedynczemu indeksowi.

In [153]:
M[0]

array([0.87590557, 0.95846158, 0.72842298])

Dostęp do wszystkich elementów w danym wierszu lub kolumnie uzyskujemy, wpisując zamiast indeksu, znak `:`.

In [154]:
M[1,:] # drugi (z kolei) wiersz (efekt identyczny z M[1])

array([0.4142462 , 0.0427534 , 0.80001726])

In [155]:
M[:,1] # kolumna o indeksie 1 (druga z kolei)

array([0.95846158, 0.0427534 , 0.31718671])

Odwołując się do elementów o konkretnych indeksach możmy także dokonać przypisania wartości:

In [156]:
M[0,0] = 1

In [157]:
M

array([[1.        , 0.95846158, 0.72842298],
       [0.4142462 , 0.0427534 , 0.80001726],
       [0.99148644, 0.31718671, 0.44461764]])

In [158]:
# podobnie dla całych wierszy i kolumn
M[1,:] = 88
M[:,2] = 123

In [159]:
M

array([[  1.        ,   0.95846158, 123.        ],
       [ 88.        ,  88.        , 123.        ],
       [  0.99148644,   0.31718671, 123.        ]])

### 4.5 Podmacierze

Podmacierz danej macierzy uzyskujemy ideksując następująco: `M[lower:upper:step]`

In [2]:
A = np.array([1,2,3,4,5])
A

NameError: name 'np' is not defined

In [3]:
A[1:3]

NameError: name 'A' is not defined

Poprzez powyższy sposób indeksowania można także zmieniać wartości elementów macierzy:

In [4]:
A[1:3] = [-2,-3]

A

NameError: name 'A' is not defined

Dowolny z trzech parametrów `M[lower:upper:step]` można pominąć:

In [5]:
A[::] # wartości domyślne - cała macierz

NameError: name 'A' is not defined

In [356]:
A[::2] # co drugi element

array([ 1, -3,  5])

In [357]:
A[:3] # pierwsze trzy elementy

array([ 1, -2, -3])

In [358]:
A[3:] # elementy od trzeciego w górę

array([4, 5])

Indeksy ujemne to liczenie od końca:

In [359]:
A = np.array([1,2,3,4,5])

In [360]:
A[-1] # ostatni element

5

In [361]:
A[-3:] # ostatnie trzy elementy

array([3, 4, 5])

Analogicznie dla macierzy wielowymiarowych:

In [163]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [164]:
# podmacierz - usuwamy ostatni wiersz i kolumnę
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [165]:
# co drugi element
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

Indeksowanie przez podanie wektora numerów indeksów 

In [166]:
indeksy_wierszy = [1, 2, 3]
A[indeksy_wierszy]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [167]:
indeksy_kolumn = [1, 2, -1] 
A[:,indeksy_kolumn]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34],
       [41, 42, 44]])

Podanie dwóch wektorów pozwala na ekstrakcję elementów macierzy położonych w wierszach i kolumnach o indeksach zawartych w odpowiednich wektorach.

In [168]:
indeksy_kolumn = [1, 2, -1] 
A[indeksy_wierszy,indeksy_kolumn]

array([11, 22, 34])

Indeksowanie jest możliwe także z wykorzystaniem masek binarnych typu `bool`, wskazujących (poprzez wartości `True`) na pożądane elementy (indeksowanie logiczne).


In [169]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [170]:
maska = np.array([True, False, True, False, False])
B[maska]

array([0, 2])

In [171]:
# to samo inaczej
maska = np.array([1,0,1,0,0], dtype=bool)
B[maska]

array([0, 2])

Stosując ten typ indeksowania można wybierać te elementy macierzy, które spełniają warunek logiczny:

In [172]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [173]:
maska = (5 < x) * (x < 7.5)

maska

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [174]:
x[maska]

array([5.5, 6. , 6.5, 7. ])

### 4.6 Podstawowe operatory

Operacje arytmetyczne

In [175]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [176]:
v1 * 2

array([0, 2, 4, 6, 8])

In [177]:
v1 + 2

array([2, 3, 4, 5, 6])

In [178]:
print(A, "\n\n", A * 2 , "\n\n", A + 2)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]] 

 [[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]] 

 [[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]]


W przypadku mnożenia standardowo wykonywane jest mnożenie **element-po-elemencie**:

In [179]:
A * A 

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [180]:
v1 * v1

array([ 0,  1,  4,  9, 16])

Przypadek dwóch macierzy:

In [181]:
A.shape, v1.shape

((5, 5), (5,))

In [182]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

Mnożenie macierzowe wymaga użycia funkcji `dot`:

In [183]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [184]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [185]:
np.dot(v1, v1)

30

Alternatywnie można użyć operatora `@`

In [186]:
v1@v1

30

### 4.7 Statystyki opisowe

Pakiet `numpy` oferuje szereg funkcji wyznaczających podstawowe statystyki opisowe. 

In [1]:
print(A)
# wartość średnia
np.mean(A)
# odchylenie standardowe i wariancja
#np.std(A[:,3]), np.var(A[:,3]), np.min(A[:,2]), np.max(A[:,2])
# wartości minimalne i maksymalne


NameError: name 'A' is not defined

In [188]:
d = np.arange(0, 10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
# suma
np.sum(d)

45

In [190]:
# iloczyn elementów
np.prod(d+1)

3628800

In [191]:
# sumy skumulowane
np.cumsum(d)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [192]:
# iloczyny skumulowane
np.cumprod(d+1)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

### 4.8 Łączenie, przekształcanie i kopiowanie macierzy

Z pomocą funkcji `repeat`, `tile`, `vstack`, `hstack`, oraz `concatenate` można tworzyć większe macierze przez zwielokrotnianie mniejszych. Instrukcja `repeat` powtarza zadaną macierz ustaloną ilość razy.

In [193]:
a = np.array([[1, 2], [3, 4]])

In [194]:
# każdy element powtórzony 3 razy
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [195]:
# nowa macierz stworzona poprzez trzykrotne powtórzenie starej
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

Instrukcje `concatenate`, `hstack` i `vstack` służą do łączenia macierzy.

In [196]:
b = np.array([[5, 6]])

In [197]:
# sklejanie macierzy
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [198]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [199]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [200]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

Macierz może być kopiowana na dwa sposoby. Typowe odwołanie do macierzy jest odwołaniem przez referencję (nazwa jest wskaźnikiem). 

In [201]:
A = np.array([[1, 2], [3, 4]])

A

array([[1, 2],
       [3, 4]])

In [202]:
# B wskazuje na ten sam obszar pamięci co A
B = A 

In [203]:
# zmiana w B wpływa na A
B[0,0] = 10

B

array([[10,  2],
       [ 3,  4]])

Nie zawsze taki sposób zachowania jest pożądany. Gdy konieczne jest pozyskanie wiernej kopii oryginalnej macierzy (kopia głęboka), umieszczonej w odrębnym miejscu w pamięci, konieczne jest zastosowanie funkcji `copy`.

In [204]:
A

array([[10,  2],
       [ 3,  4]])

In [205]:
C = np.copy(A)

In [206]:
# teraz, modyfikując B nie wpływamy na A
C[0,0] = -5
C

array([[-5,  2],
       [ 3,  4]])

In [207]:
A

array([[10,  2],
       [ 3,  4]])

Informację o tym, czy dane dwie zmienne odnoszą się do tej samej czy też różnych macierzy, można uzyskać korzystając z komendy `is`

In [208]:
print ("Czy A i B to ta sama macierz ?" , A is B)
print ("Czy A i C to ta sama macierz ?" , A is C)

Czy A i B to ta sama macierz ? True
Czy A i C to ta sama macierz ? False


## Dla dociekliwych

* http://www.python.org/dev/peps/pep-0008 - Księga stylu, czyli zalecenia odnośnie stylu programowania w Pythonie. 
* https://greenteapress.com/wp/think-python-2e/ - Darmowa książka

---
---
Historia zmian:
* wersja pierwotna r.akad 18/19: 17.03.2019 (MI)
* wersja r.akad 19/20: 6.03.2020 (MI)
* wersja r.akad 19/20: 21.03.2020 (GS)
* wersja r.akad 24/25: 9.10.2024 (MI)